// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9Snfz28PxgkHqVtoniV1fu3RgEOMW9Wo',
    appId: '1:1063487659350:web:d3181a012e842c6b24caf7',
    messagingSenderId: '1063487659350',
    projectId: 'nyam228-374b1',
    authDomain: 'nyam228-374b1.firebaseapp.com',
    storageBucket: 'nyam228-374b1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApf-sUaOG-47mgw9nftud5bSc5rFFuhOk',
    appId: '1:1063487659350:android:be4d019fc02f384c24caf7',
    messagingSenderId: '1063487659350',
    projectId: 'nyam228-374b1',
    storageBucket: 'nyam228-374b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhuZqr-S8naffkFq0lYAj0QKEmZQA-9JQ',
    appId: '1:1063487659350:ios:d4a78a3a4687350524caf7',
    messagingSenderId: '1063487659350',
    projectId: 'nyam228-374b1',
    storageBucket: 'nyam228-374b1.appspot.com',
    iosBundleId: 'com.example.nyam228',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhuZqr-S8naffkFq0lYAj0QKEmZQA-9JQ',
    appId: '1:1063487659350:ios:d4a78a3a4687350524caf7',
    messagingSenderId: '1063487659350',
    projectId: 'nyam228-374b1',
    storageBucket: 'nyam228-374b1.appspot.com',
    iosBundleId: 'com.example.nyam228',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9Snfz28PxgkHqVtoniV1fu3RgEOMW9Wo',
    appId: '1:1063487659350:web:b54a71a413bbcb6f24caf7',
    messagingSenderId: '1063487659350',
    projectId: 'nyam228-374b1',
    authDomain: 'nyam228-374b1.firebaseapp.com',
    storageBucket: 'nyam228-374b1.appspot.com',
  );
}
